language: js

script:
  - echo "no build required"

deploy:
  - provider: lambda
    function_name: "lambda-travis-js"
    runtime: "nodejs8.10"

    # AWS Region (Ireland)
    region: "eu-west-1"
    # AWS IAM
    role: "arn:aws:iam::854014537498:role/lambda_basic_execution"

    # name of js file
    module_name: "lambda_handler" 
    handler_name: "call"
    # deploy on branch js
    on: js
