language: java

deploy:
  - provider: lambda
    function_name: "lambda-travis-java"
    region: "eu-west-1"
    role: "arn:aws:iam::854014537498:role/lambda_basic_execution"
    runtime: "java8"

    module_name: "com.schneidernet.Handler" 
    handler_name: "handleRequest"
    on: java

