language: js

script:
  - ls -lah

deploy:
  - provider: lambda
    function_name: "lambda-travis-js"
    region: "	eu-west-1"
    role: "arn:aws:iam::854014537498:role/lambda_basic_execution"
    runtime: "nodejs8.10"
    handler_name: "lambda_handler.call"
#    zip: lambda_handler.zip
    skip_cleanup: true
    on: js
