language: go

# override default build command
script: 
  - go build -o lambda_handler.bin lambda_handler.go
#  - zip lambda_handler.zip lambda_handler

deploy:
  - provider: lambda
    function_name: "lambda-travis-go"
    region: "eu-west-1"
    role: "arn:aws:iam::854014537498:role/lambda_basic_execution"
    runtime: "go1.x"
 
    # workaround, for handler_name (concated via .)
    module_name: "lambda_handler"
    handler_name: "bin"
 
    on: go
#    skip_cleanup: true
#    zip: lambda_handler.zip
