language: csharp
mono: none
dotnet: 2.2

# override default build command
script: 
  - cd src/MyFunction
  - dotnet info
  - dotnet restore
  - dotnet list package
  - dotnet tool list -g
  - dotnet lambda deploy-function

deploy:
  - provider: lambda
    function_name: "lambda-travis-go"
    region: "eu-west-1"
    role: "arn:aws:iam::854014537498:role/lambda_basic_execution"
    runtime: "dotnet"
 
    # workaround, for handler_name (concated via .)
    module_name: "lambda_handler"
    handler_name: "bin"
 
    on: go