language: go

# override default build command
script: go build lambda_handler.go

before_deploy:
  - ls -lah
  - find .

deploy:
  - provider: lambda
    skip_cleanup: true
    function_name: "lambda-travis-go"
    region: "eu-west-1"
    role: "arn:aws:iam::854014537498:role/lambda_basic_execution"
    runtime: "go1.x"
    handler_name: "lambda_handler"
    on: go
    zip: .

after_deploy:
  - ls -lah
  - ls -lah $TMP
  - for %a in /tmp/*.zip; do unzip -t $a; done
  