language: python

script: 
  - echo "no build required"

deploy:
  - provider: lambda
    function_name: "lambda-travis-python"
    runtime: "python3.7"

    region: "eu-west-1"
    role: "arn:aws:iam::854014537498:role/lambda_basic_execution"
    
    # name of python file
    module_name: "lambda_handler" 
    # name of fn
    handler_name: "call"          

    on: python