language: csharp
mono: none

# AWS Supported
dotnet: 2.1.403   


# override default build command
script: 
  - dotnet restore
  - dotnet test
  - cd src/MyFunction
  - dotnet lambda deploy-function

deploy:
  - provider: lambda
    function_name: "lambda-travis-dotnet"
    region: "eu-west-1"
    role: "arn:aws:iam::854014537498:role/lambda_basic_execution"
    runtime: "dotnet"
 
    # workaround, for handler_name (concated via .)
    module_name: "lambda_handler"
    handler_name: "bin"
 
    on: dotnet